version = 0.1
[default.deploy.parameters]
stack_name = "customer-api"
resolve_s3 = true
s3_prefix = "customer-api"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "Environment=\"Dev\" TableName=\"CustomerTable\""
image_repositories = []
